
SELECT COUNT(*) AS arrest_borough FROM dbo.dim_arrest_borough
SELECT COUNT(*) AS BODILY_INJURY FROM dbo.Dim_BODILY_INJURY
SELECT COUNT(*) AS COMPLAINT FROM dbo.Dim_COMPLAINT
SELECT COUNT(*) AS Dim_CONTRIBUTING_FACTOR FROM dbo.Dim_CONTRIBUTING_FACTOR
SELECT COUNT(*) AS DRIVER_LICENSE_JURISDICTION FROM dbo.Dim_DRIVER_LICENSE_JURISDICTION
SELECT COUNT(*) AS DRIVER_LICENSE_STATUS FROM dbo.Dim_DRIVER_LICENSE_STATUS
SELECT COUNT(*) AS EJECTION FROM dbo.Dim_EJECTION

SELECT COUNT(*) AS EMOTIONAL_STATUS FROM dbo.Dim_EMOTIONAL_STATUS
SELECT COUNT(*) AS Dim_PED_ACTION From dbo.Dim_PED_ACTION
SELECT COUNT(*) AS PED_LOCATION FROM dbo.Dim_PED_LOCATION
SELECT COUNT(*) AS PED_ROLE FROM dbo.Dim_PED_ROLE
SELECT COUNT(*) AS PERSON_INJURY FROM dbo.Dim_PERSON_INJURY
SELECT COUNT(*) AS Dim_PERSON_SEX FROM dbo.Dim_PERSON_SEX
SELECT COUNT(*) AS Dim_PersonType FROM dbo.Dim_PersonType

SELECT COUNT(*) AS POINT_OF_IMPACT FROM dbo.Dim_POINT_OF_IMPACT
SELECT COUNT(*) AS POSITION_IN_VEHICLE FROM dbo.Dim_POSITION_IN_VEHICLE
SELECT COUNT(*) AS PRE_CRASH FROM dbo.Dim_PRE_CRASH
SELECT COUNT(*) AS PUBLIC_PROPERTY_DAMAGE FROM dbo.Dim_PUBLIC_PROPERTY_DAMAGE
SELECT COUNT(*) AS SAFETY_EQUIPMENT FROM dbo.Dim_SAFETY_EQUIPMENT
SELECT COUNT(*) AS STATE_REGISTRATION FROM dbo.Dim_STATE_REGISTRATION
SELECT COUNT(*) AS TRAVEL_DIRECTION FROM dbo.Dim_TRAVEL_DIRECTION
SELECT COUNT(*) AS VEHICLE_DAMAGE FROM dbo.Dim_VEHICLE_DAMAGE
SELECT COUNT(*) AS VEHICLE_MAKE FROM dbo.Dim_VEHICLE_MAKE
SELECT COUNT(*) AS VEHICLE_MODEL FROM dbo.Dim_VEHICLE_MODEL
SELECT COUNT(*) AS VEHICLE_TYPE FROM dbo.Dim_VEHICLE_TYPE

SELECT COUNT(*) AS collision_crashes  FROM dbo.fct_collision_crashes
SELECT COUNT(*) AS collision_crashes_vehicles FROM dbo.fct_collision_crashes_vehicles
SELECT COUNT(*) AS collision_persons FROM dbo.fct_collision_persons
SELECT COUNT(*) AS persons_contributing_factors FROM dbo.fct_collision_persons_contributing_factors
SELECT COUNT(*) AS fct_Collisions_Vehicles FROM dbo.fct_Collisions_Vehicles
SELECT COUNT(*) FROM dbo.fct_Collisions_Vehicles_Contributing_Factors
SELECT COUNT(*) FROM dbo.fct_Collisions_Vehicles_Vehicle_Damage
SELECT COUNT(*) FROM dbo.stg_nyc_mv_collision_persons
SELECT COUNT(*) FROM dbo.stg_nyc_mv_collision_vehicles
SELECT COUNT(*) FROM dbo.stg_nyc_mv_collisions_BigQuery


